apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nodejs-pipeline-run-
spec:
  pipelineRef:
    name: nodejs-pipeline
  serviceAccountName: build-bot
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes: 
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi