apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: galatrog-app
  app.kubernetes.io/instance: galatrog-app-instance
  app.kubernetes.io/name: galatrog-app
