apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
  tasks:
    - name: clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: https://github.com/galatro/galatro-tekton-build
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: build-and-push-image
      runAfter:
        - clone
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: "quay.io/galatro/galatro-app:$(tasks.clone.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: kustomize
      runAfter:
        - build-and-push-image
      taskRef:
        name: kustomize
      params:
        - name: app-name
          value: galatrog-app
        - name: app-namespace
          value: "$(context.pipelineRun.namespace)"
        - name: source-repo
          value: https://github.com/galatro/galatro-tekton-build
        - name: commit
          value: "$(tasks.clone.results.commit)"
        - name: image-repo
          value: quay.io/galatro/galatro-app
      workspaces:
        - name: source
          workspace: pipeline-shared-data
