apiVersion: v1
kind: ServiceAccount
metadata:
  name: galatro-assignment-trigger
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: galatro-assignment-trigger
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: galatro-assignment-trigger
subjects:
  - kind: ServiceAccount
    name: galatro-assignment-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: galatro-assignment-trigger
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: galatro-assignment-trigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      generateName: nodejs-pipeline-run-
      spec:
        pipelineRef:
          name: nodejs-pipeline
        serviceAccountName: build-bot
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes: 
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: galatro-assignment-trigger
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: galatro-assignment-trigger
spec:
  serviceAccountName: galatro-assignment-trigger
  triggers:
    - bindings:
        - ref: galatro-assignment-trigger
      template:
        name: galatro-assignment-trigger
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: galatro-assignment-trigger
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-galatro-assignment-trigger
    weight: 100